import { useState } from "react";
import {
  FaBookOpen,
  FaDatabase,
  FaFlask,
  FaGlobe,
  FaGraduationCap,
  FaMagnifyingGlass,
  FaCompass,
} from "react-icons/fa6";

import Sidebar from "../components/Sidebar";
import ChatBox from "../components/ChatBox";

const sectionConfig = {
  search: {
    label: "Search",
    title: "Research Search",
    description: "Search across uploaded papers, notes, and indexed research snippets.",
    icon: FaMagnifyingGlass,
    cards: [
      "Semantic search across your indexed PDFs",
      "Quick prompts for finding methods, findings, and citations",
      "A launch point into deeper chat-based exploration",
    ],
  },
  navigator: {
    label: "Science Navigator",
    title: "Science Navigator",
    description: "Map a topic into questions, methods, datasets, and next research directions.",
    icon: FaCompass,
    cards: [
      "Break complex topics into step-by-step sub-questions",
      "Identify likely experiments, baselines, and evaluation angles",
      "Turn broad ideas into a research plan you can execute",
    ],
  },
  library: {
    label: "Library",
    title: "Document Library",
    description: "A home for uploaded documents and summaries generated by the assistant.",
    icon: FaBookOpen,
    cards: [
      "Upload PDFs and get instant summaries",
      "Keep a growing searchable knowledge collection",
      "Use documents directly as context for questions",
    ],
  },
  scholars: {
    label: "Scholars",
    title: "Scholars Workspace",
    description: "A place to organize authors, papers, and topic-specific reading tracks.",
    icon: FaGraduationCap,
    cards: [
      "Track important authors and recurring concepts",
      "Group papers by theme, method, or dataset",
      "Build reading lists around a literature review",
    ],
  },
  sciencepedia: {
    label: "SciencePedia",
    title: "SciencePedia",
    description: "Browse concept-oriented explanations for technical topics and terminology.",
    icon: FaGlobe,
    cards: [
      "Get plain-language explanations of scientific terms",
      "Connect concepts to methods and applications",
      "Use as a glossary while reading dense papers",
    ],
  },
  knowledge: {
    label: "Knowledge Base",
    title: "Knowledge Base",
    description: "Structured reference space for extracted insights, notes, and reusable findings.",
    icon: FaDatabase,
    cards: [
      "Store summarized knowledge from uploaded files",
      "Build reusable context for future conversations",
      "Create a persistent research memory over time",
    ],
  },
  practice: {
    label: "Practice",
    title: "Practice Lab",
    description: "Use guided exercises, writing drills, and experimentation prompts.",
    icon: FaFlask,
    cards: [
      "Turn concepts into exercises or writing prompts",
      "Practice explaining methods in your own words",
      "Stress-test understanding before presentations or reviews",
    ],
  },
};

function SectionPanel({ sectionKey, onOpenChat }) {
  const section = sectionConfig[sectionKey];
  const Icon = section.icon;

  return (
    <section className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-[36px] border border-white/60 bg-[linear-gradient(180deg,rgba(255,255,255,0.82),rgba(242,246,255,0.92))] p-6 shadow-[0_40px_110px_rgba(120,138,204,0.18)] backdrop-blur-2xl md:p-8">
      <div className="mb-8 flex flex-wrap items-start justify-between gap-5">
        <div className="max-w-3xl">
          <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-[24px] bg-[linear-gradient(135deg,#4c69ed,#9bb1ff)] text-2xl text-white shadow-[0_18px_38px_rgba(73,104,235,0.26)]">
            <Icon />
          </div>
          <p className="text-sm font-semibold uppercase tracking-[0.28em] text-[#6e85df]">
            {section.label}
          </p>
          <h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-800 md:text-5xl">
            {section.title}
          </h1>
          <p className="mt-4 max-w-2xl text-sm leading-7 text-slate-500 md:text-base">
            {section.description}
          </p>
        </div>

        <button
          onClick={onOpenChat}
          className="rounded-2xl bg-[#4968eb] px-5 py-3 text-sm font-semibold text-white shadow-[0_18px_35px_rgba(73,104,235,0.28)] transition hover:-translate-y-0.5 hover:bg-[#3f5bdd]"
        >
          Open Research Chat
        </button>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        {section.cards.map((card) => (
          <div
            key={card}
            className="rounded-[28px] border border-white/80 bg-white/80 p-5 shadow-[0_18px_36px_rgba(137,154,204,0.12)]"
          >
            <p className="text-base font-semibold text-slate-800">{card}</p>
            <p className="mt-3 text-sm leading-6 text-slate-500">
              This section is now active and ready for the next step of implementation.
            </p>
          </div>
        ))}
      </div>

      <div className="mt-6 rounded-[30px] border border-dashed border-[#c7d2fe] bg-[linear-gradient(180deg,rgba(238,242,255,0.8),rgba(255,255,255,0.7))] p-6">
        <h2 className="text-lg font-semibold text-slate-800">What works now</h2>
        <p className="mt-3 text-sm leading-7 text-slate-600">
          Clicking sidebar items now switches the main dashboard panel. The content here is a
          functional section view so the menu no longer feels broken, and you can jump back into
          the assistant at any time.
        </p>
      </div>
    </section>
  );
}

export default function Dashboard() {
  const [activeSection, setActiveSection] = useState("chat");

  return (
    <div className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top_left,rgba(222,231,255,0.95),rgba(241,245,255,0.92)_38%,rgba(231,237,255,0.84)_72%,rgba(221,228,250,0.75))] p-3 text-slate-900 md:p-5">
      <div className="relative mx-auto flex min-h-[calc(100vh-24px)] max-w-[1600px] gap-4 overflow-hidden rounded-[40px] border border-white/60 bg-[linear-gradient(180deg,rgba(247,249,255,0.78),rgba(235,240,255,0.72))] p-3 shadow-[0_45px_120px_rgba(148,163,218,0.24)] md:min-h-[calc(100vh-40px)] md:gap-6 md:p-5">
        <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(113,140,243,0.18),transparent_30%),radial-gradient(circle_at_bottom_left,rgba(255,255,255,0.8),transparent_28%)]" />
        <div className="relative hidden xl:block">
          <Sidebar activeSection={activeSection} onSectionChange={setActiveSection} />
        </div>
        <div className="relative flex min-w-0 flex-1">
          {activeSection === "chat" ? (
            <ChatBox />
          ) : (
            <SectionPanel sectionKey={activeSection} onOpenChat={() => setActiveSection("chat")} />
          )}
        </div>
      </div>
    </div>
  );
}
